datafile: "Bovin_lens.imzML"
Digestion_site: "trypsin"
Thread: 1
Fastadatabase: "uniprot-bovin.fasta"
mode: ["Proteomics","Metabolomics"]
mzrange:  [500, 5000]
adducts: ["M+H"]
Multiple_mode: ["sequential","parallel"]
Decoy_adducts: ["M+ACN+H","M+IsoProp+H","M+DMSO+H","M+Co","M+Ag","M+Cu","M+He","M+Ne","M+Ar","M+Kr","M+Xe","M+Rn"]
Decoy_search: TRUE
Decoy_mode: "isotope"
use_previous_candidates: TRUE
missedCleavages: [0, 1]
Substitute_AA: NULL
projectfolder: NULL
IMS_analysis : TRUE
threshold : 0.001
ppm : 5
Segmentation : ["spatialKMeans","spatialShrunkenCentroids","Virtual_segmentation","none","def_file"]
Virtual_segmentation_rankfile : NULL
Bypass_generate_spectrum : FALSE
spectra_segments_per_file : 1
Rotate_IMG : NULL
Segmentation_ncomp : "auto-detect"
score_method : "SQRTP"
adjust_score : FALSE
peptide_ID_filter : 2
Protein_desc_of_interest : "."
plot_matching_score : FALSE
FDR_cutoff : 0.05
Segmentation_def : "Segmentation_def.csv"
Segmentation_variance_coverage : 0.8
preprocess:
  force_preprocess: false
  use_preprocessRDS: true
  smoothSignal:
    method: Disable
  reduceBaseline:
    method: Disable
  peakPick:
    method: simple
  peakAlign:
    tolerance: 2.5
    units: ppm
  normalize:
    method: Disable
    mz: 1
Modifications:
  fixed: NULL
  fixmod_position: NULL
  variable : NULL
  varmod_positions: NULL
  one_letter : NULL
  # variable:
  #   - "Hydroxylation"
  #   - "Hydroxylation"
  #   - "Hydroxylation"
  #   - "Hydroxylation"
  #   - "Deamidation"
  #   - "Deamidation"
  #   - "Pyro-glu"
  #   - "Formyl"
  #   - "Methyl"
  #   - "Methyl"
  # varmod_positions:
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  # one_letter:
  #   - "M"
  #   - "P"
  #   - "K"
  #   - "D"
  #   - "Q"
  #   - "N"
  #   - "E"
  #   - "K"
  #   - "R"
  #   - "K"

Protein_feature_summary : TRUE
Peptide_feature_summary : TRUE
Region_feature_summary : FALSE
plot_cluster_image_grid : TRUE
remove_score_outlier : FALSE

Plot_score_IQR_cutoff : 0.75
Plot_score_abs_cutoff : -0.1
cluster_rds_path : NULL
mzAlign_runs : "TopNfeature_mean"
deconv_peaklist : "New"
plot_unique_component : TRUE